[package]
name = "cube"
version = "0.1.0"
edition = "2024"
description = "Simple cube example using fastn"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
fastn = { path = "../../fastn" }
